export type TSS2_RC = number;

export const TSS2_RC_LAYER_SHIFT = 16;

export const TSS2_RC_LAYER = (level: number) => {
  return (level << TSS2_RC_LAYER_SHIFT) >>> 0;
};

export const u = (val: number) => {
  return val >>> 0;
};

export const TSS2_RC_LAYER_MASK: TSS2_RC = TSS2_RC_LAYER(0xff);

export const layers = {
  TSS2_TPM_RC_LAYER: TSS2_RC_LAYER(0),
  TSS2_FEATURE_RC_LAYER: TSS2_RC_LAYER(6),
  TSS2_ESAPI_RC_LAYER: TSS2_RC_LAYER(7),
  TSS2_SYS_RC_LAYER: TSS2_RC_LAYER(8),
  TSS2_MU_RC_LAYER: TSS2_RC_LAYER(9),
  TSS2_TCTI_RC_LAYER: TSS2_RC_LAYER(10),
  TSS2_RESMGR_RC_LAYER: TSS2_RC_LAYER(11),
  TSS2_RESMGR_TPM_RC_LAYER: TSS2_RC_LAYER(12),
};

/* Base return codes.
 * These base codes indicate the error that occurred. They are
 * logical-ORed with a layer code to produce the TSS2 return value.
 */
export const base = {
  TSS2_BASE_RC_GENERAL_FAILURE:
    u(1) /* Catch all for all errors not otherwise specified */,
  TSS2_BASE_RC_NOT_IMPLEMENTED:
    u(2) /* If called functionality isn't implemented */,
  TSS2_BASE_RC_BAD_CONTEXT: u(3) /* A context structure is bad */,
  TSS2_BASE_RC_ABI_MISMATCH:
    u(4) /* Passed in ABI version doesn't match called module's ABI version */,
  TSS2_BASE_RC_BAD_REFERENCE:
    u(5) /* A pointer is NULL that isn't allowed to be NULL. */,
  TSS2_BASE_RC_INSUFFICIENT_BUFFER: u(6) /* A buffer isn't large enough */,
  TSS2_BASE_RC_BAD_SEQUENCE: u(7) /* Function called in the wrong order */,
  TSS2_BASE_RC_NO_CONNECTION: u(8) /* Fails to connect to next lower layer */,
  TSS2_BASE_RC_TRY_AGAIN:
    u(
      9
    ) /* Operation timed out; function must be called again to be completed */,
  TSS2_BASE_RC_IO_ERROR: u(10) /* IO failure */,
  TSS2_BASE_RC_BAD_VALUE: u(11) /* A parameter has a bad value */,
  TSS2_BASE_RC_NOT_PERMITTED: u(12) /* Operation not permitted. */,
  TSS2_BASE_RC_INVALID_SESSIONS:
    u(
      13
    ) /* Session structures were sent, but command doesn't use them or doesn't use the specifed, number of them */,
  TSS2_BASE_RC_NO_DECRYPT_PARAM:
    u(
      14
    ) /* If function called that uses decrypt parameter, but command doesn't support crypt parameter. */,
  TSS2_BASE_RC_NO_ENCRYPT_PARAM:
    u(
      15
    ) /* If function called that uses encrypt parameter, but command doesn't support encrypt parameter. */,
  TSS2_BASE_RC_BAD_SIZE: u(16) /* If size of a parameter is incorrect */,
  TSS2_BASE_RC_MALFORMED_RESPONSE: u(17) /* Response is malformed */,
  TSS2_BASE_RC_INSUFFICIENT_CONTEXT: u(18) /* Context not large enough */,
  TSS2_BASE_RC_INSUFFICIENT_RESPONSE: u(19) /* Response is not long enough */,
  TSS2_BASE_RC_INCOMPATIBLE_TCTI: u(20) /* Unknown or unusable TCTI version */,
  TSS2_BASE_RC_NOT_SUPPORTED: u(21) /* Functionality not supported. */,
  TSS2_BASE_RC_BAD_TCTI_STRUCTURE: u(22) /* TCTI context is bad. */,
  TSS2_BASE_RC_MEMORY: u(23) /* memory allocation failed */,
  TSS2_BASE_RC_BAD_TR: u(24) /* invalid ESYS_TR handle */,
  TSS2_BASE_RC_MULTIPLE_DECRYPT_SESSIONS:
    u(25) /* More than one session with TPMA_SESSION_DECRYPT bit set */,
  TSS2_BASE_RC_MULTIPLE_ENCRYPT_SESSIONS:
    u(26) /* More than one session with TPMA_SESSION_ENCRYPT bit set */,
  TSS2_BASE_RC_RSP_AUTH_FAILED:
    u(27) /* Response HMAC from TPM did not verify */,
  TSS2_BASE_RC_NO_CONFIG: u(28),
  TSS2_BASE_RC_BAD_PATH: u(29),
  TSS2_BASE_RC_NOT_DELETABLE: u(30),
  TSS2_BASE_RC_PATH_ALREADY_EXISTS: u(31),
  TSS2_BASE_RC_KEY_NOT_FOUND: u(32),
  TSS2_BASE_RC_SIGNATURE_VERIFICATION_FAILED: u(33),
  TSS2_BASE_RC_HASH_MISMATCH: u(34),
  TSS2_BASE_RC_KEY_NOT_DUPLICABLE: u(35),
  TSS2_BASE_RC_PATH_NOT_FOUND: u(36),
  TSS2_BASE_RC_NO_CERT: u(37),
  TSS2_BASE_RC_NO_PCR: u(38),
  TSS2_BASE_RC_PCR_NOT_RESETTABLE: u(39),
  TSS2_BASE_RC_BAD_TEMPLATE: u(40),
  TSS2_BASE_RC_AUTHORIZATION_FAILED: u(41),
  TSS2_BASE_RC_AUTHORIZATION_UNKNOWN: u(42),
  TSS2_BASE_RC_NV_NOT_READABLE: u(43),
  TSS2_BASE_RC_NV_TOO_SMALL: u(44),
  TSS2_BASE_RC_NV_NOT_WRITEABLE: u(45),
  TSS2_BASE_RC_POLICY_UNKNOWN: u(46),
  TSS2_BASE_RC_NV_WRONG_TYPE: u(47),
  TSS2_BASE_RC_NAME_ALREADY_EXISTS: u(48),
  TSS2_BASE_RC_NO_TPM: u(49),
  TSS2_BASE_RC_BAD_KEY: u(50),
  TSS2_BASE_RC_NO_HANDLE: u(51),
  TSS2_BASE_RC_NOT_PROVISIONED: u(52),
  TSS2_BASE_RC_ALREADY_PROVISIONED: u(53),
  TSS2_BASE_RC_CALLBACK_NULL: u(54),
};

const enums = {
  /* Base return codes in the range 0xf800 - 0xffff are reserved for
   * implementation-specific purposes.
   */
  TSS2_LAYER_IMPLEMENTATION_SPECIFIC_OFFSET: 0xf800,
  TSS2_LEVEL_IMPLEMENTATION_SPECIFIC_SHIFT: 11,

  /* Success is the same for all software layers */
  TSS2_RC_SUCCESS: 0,

  /* TCTI error codes */
  TCTI: {
    TSS2_TCTI_RC_GENERAL_FAILURE:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_GENERAL_FAILURE,
    TSS2_TCTI_RC_NOT_IMPLEMENTED:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_NOT_IMPLEMENTED,
    TSS2_TCTI_RC_BAD_CONTEXT:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_BAD_CONTEXT,
    TSS2_TCTI_RC_ABI_MISMATCH:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_ABI_MISMATCH,
    TSS2_TCTI_RC_BAD_REFERENCE:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_BAD_REFERENCE,
    TSS2_TCTI_RC_INSUFFICIENT_BUFFER:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_BUFFER,
    TSS2_TCTI_RC_BAD_SEQUENCE:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_BAD_SEQUENCE,
    TSS2_TCTI_RC_NO_CONNECTION:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_NO_CONNECTION,
    TSS2_TCTI_RC_TRY_AGAIN:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_TRY_AGAIN,
    TSS2_TCTI_RC_IO_ERROR:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_IO_ERROR,
    TSS2_TCTI_RC_BAD_VALUE:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_BAD_VALUE,
    TSS2_TCTI_RC_NOT_PERMITTED:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_NOT_PERMITTED,
    TSS2_TCTI_RC_MALFORMED_RESPONSE:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_MALFORMED_RESPONSE,
    TSS2_TCTI_RC_NOT_SUPPORTED:
      layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_NOT_SUPPORTED,
    TSS2_TCTI_RC_MEMORY: layers.TSS2_TCTI_RC_LAYER | base.TSS2_BASE_RC_MEMORY,
  },

  /* SAPI error codes */
  SYS: {
    TSS2_SYS_RC_GENERAL_FAILURE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_GENERAL_FAILURE,
    TSS2_SYS_RC_ABI_MISMATCH:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_ABI_MISMATCH,
    TSS2_SYS_RC_BAD_REFERENCE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_BAD_REFERENCE,
    TSS2_SYS_RC_INSUFFICIENT_BUFFER:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_BUFFER,
    TSS2_SYS_RC_BAD_SEQUENCE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_BAD_SEQUENCE,
    TSS2_SYS_RC_BAD_VALUE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_BAD_VALUE,
    TSS2_SYS_RC_INVALID_SESSIONS:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_INVALID_SESSIONS,
    TSS2_SYS_RC_NO_DECRYPT_PARAM:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_NO_DECRYPT_PARAM,
    TSS2_SYS_RC_NO_ENCRYPT_PARAM:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_NO_ENCRYPT_PARAM,
    TSS2_SYS_RC_BAD_SIZE: layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_BAD_SIZE,
    TSS2_SYS_RC_MALFORMED_RESPONSE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_MALFORMED_RESPONSE,
    TSS2_SYS_RC_INSUFFICIENT_CONTEXT:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_CONTEXT,
    TSS2_SYS_RC_INSUFFICIENT_RESPONSE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_RESPONSE,
    TSS2_SYS_RC_INCOMPATIBLE_TCTI:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_INCOMPATIBLE_TCTI,
    TSS2_SYS_RC_BAD_TCTI_STRUCTURE:
      layers.TSS2_SYS_RC_LAYER | base.TSS2_BASE_RC_BAD_TCTI_STRUCTURE,
  },

  /* MUAPI error codes */
  MU: {
    TSS2_MU_RC_GENERAL_FAILURE:
      layers.TSS2_MU_RC_LAYER | base.TSS2_BASE_RC_GENERAL_FAILURE,
    TSS2_MU_RC_BAD_REFERENCE:
      layers.TSS2_MU_RC_LAYER | base.TSS2_BASE_RC_BAD_REFERENCE,
    TSS2_MU_RC_BAD_SIZE: layers.TSS2_MU_RC_LAYER | base.TSS2_BASE_RC_BAD_SIZE,
    TSS2_MU_RC_BAD_VALUE: layers.TSS2_MU_RC_LAYER | base.TSS2_BASE_RC_BAD_VALUE,
    TSS2_MU_RC_INSUFFICIENT_BUFFER:
      layers.TSS2_MU_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_BUFFER,
  },

  /* ESAPI Error Codes */
  ESYS: {
    TSS2_ESYS_RC_GENERAL_FAILURE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_GENERAL_FAILURE,
    TSS2_ESYS_RC_NOT_IMPLEMENTED:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_NOT_IMPLEMENTED,
    TSS2_ESYS_RC_ABI_MISMATCH:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_ABI_MISMATCH,
    TSS2_ESYS_RC_BAD_REFERENCE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_REFERENCE,
    TSS2_ESYS_RC_INSUFFICIENT_BUFFER:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_BUFFER,
    TSS2_ESYS_RC_BAD_SEQUENCE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_SEQUENCE,
    TSS2_ESYS_RC_INVALID_SESSIONS:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_INVALID_SESSIONS,
    TSS2_ESYS_RC_TRY_AGAIN:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_TRY_AGAIN,
    TSS2_ESYS_RC_IO_ERROR:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_IO_ERROR,
    TSS2_ESYS_RC_BAD_VALUE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_VALUE,
    TSS2_ESYS_RC_NO_DECRYPT_PARAM:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_NO_DECRYPT_PARAM,
    TSS2_ESYS_RC_NO_ENCRYPT_PARAM:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_NO_ENCRYPT_PARAM,
    TSS2_ESYS_RC_BAD_SIZE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_SIZE,
    TSS2_ESYS_RC_MALFORMED_RESPONSE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_MALFORMED_RESPONSE,
    TSS2_ESYS_RC_INSUFFICIENT_CONTEXT:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_CONTEXT,
    TSS2_ESYS_RC_INSUFFICIENT_RESPONSE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_INSUFFICIENT_RESPONSE,
    TSS2_ESYS_RC_INCOMPATIBLE_TCTI:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_INCOMPATIBLE_TCTI,
    TSS2_ESYS_RC_BAD_TCTI_STRUCTURE:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_TCTI_STRUCTURE,
    TSS2_ESYS_RC_MEMORY: layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_MEMORY,
    TSS2_ESYS_RC_BAD_TR: layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_BAD_TR,
    TSS2_ESYS_RC_MULTIPLE_DECRYPT_SESSIONS:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_MULTIPLE_DECRYPT_SESSIONS,
    TSS2_ESYS_RC_MULTIPLE_ENCRYPT_SESSIONS:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_MULTIPLE_ENCRYPT_SESSIONS,
    TSS2_ESYS_RC_NOT_SUPPORTED:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_NOT_SUPPORTED,
    TSS2_ESYS_RC_RSP_AUTH_FAILED:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_RSP_AUTH_FAILED,
    TSS2_ESYS_RC_CALLBACK_NULL:
      layers.TSS2_ESAPI_RC_LAYER | base.TSS2_BASE_RC_CALLBACK_NULL,
  },

  /* FAPI Error Codes */
  FAPI: {
    TSS2_FAPI_RC_GENERAL_FAILURE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_GENERAL_FAILURE,
    TSS2_FAPI_RC_NOT_IMPLEMENTED:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NOT_IMPLEMENTED,
    TSS2_FAPI_RC_BAD_REFERENCE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_REFERENCE,
    TSS2_FAPI_RC_BAD_SEQUENCE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_SEQUENCE,
    TSS2_FAPI_RC_IO_ERROR:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_IO_ERROR,
    TSS2_FAPI_RC_BAD_VALUE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_VALUE,
    TSS2_FAPI_RC_NO_DECRYPT_PARAM:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_DECRYPT_PARAM,
    TSS2_FAPI_RC_NO_ENCRYPT_PARAM:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_ENCRYPT_PARAM,
    TSS2_FAPI_RC_MEMORY:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_MEMORY,
    TSS2_FAPI_RC_BAD_CONTEXT:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_CONTEXT,
    TSS2_FAPI_RC_NO_CONFIG:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_CONFIG,
    TSS2_FAPI_RC_BAD_PATH:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_PATH,
    TSS2_FAPI_RC_NOT_DELETABLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NOT_DELETABLE,
    TSS2_FAPI_RC_PATH_ALREADY_EXISTS:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_PATH_ALREADY_EXISTS,
    TSS2_FAPI_RC_KEY_NOT_FOUND:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_KEY_NOT_FOUND,
    TSS2_FAPI_RC_SIGNATURE_VERIFICATION_FAILED:
      layers.TSS2_FEATURE_RC_LAYER |
      base.TSS2_BASE_RC_SIGNATURE_VERIFICATION_FAILED,
    TSS2_FAPI_RC_HASH_MISMATCH:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_HASH_MISMATCH,
    TSS2_FAPI_RC_KEY_NOT_DUPLICABLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_KEY_NOT_DUPLICABLE,
    TSS2_FAPI_RC_PATH_NOT_FOUND:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_PATH_NOT_FOUND,
    TSS2_FAPI_RC_NO_CERT:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_CERT,
    TSS2_FAPI_RC_NO_PCR:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_PCR,
    TSS2_FAPI_RC_PCR_NOT_RESETTABLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_PCR_NOT_RESETTABLE,
    TSS2_FAPI_RC_BAD_TEMPLATE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_TEMPLATE,
    TSS2_FAPI_RC_AUTHORIZATION_FAILED:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_AUTHORIZATION_FAILED,
    TSS2_FAPI_RC_AUTHORIZATION_UNKNOWN:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_AUTHORIZATION_UNKNOWN,
    TSS2_FAPI_RC_NV_NOT_READABLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NV_NOT_READABLE,
    TSS2_FAPI_RC_NV_TOO_SMALL:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NV_TOO_SMALL,
    TSS2_FAPI_RC_NV_NOT_WRITEABLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NV_NOT_WRITEABLE,
    TSS2_FAPI_RC_POLICY_UNKNOWN:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_POLICY_UNKNOWN,
    TSS2_FAPI_RC_NV_WRONG_TYPE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NV_WRONG_TYPE,
    TSS2_FAPI_RC_NAME_ALREADY_EXISTS:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NAME_ALREADY_EXISTS,
    TSS2_FAPI_RC_NO_TPM:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_TPM,
    TSS2_FAPI_RC_TRY_AGAIN:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_TRY_AGAIN,
    TSS2_FAPI_RC_BAD_KEY:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_BAD_KEY,
    TSS2_FAPI_RC_NO_HANDLE:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NO_HANDLE,
    TSS2_FAPI_RC_NOT_PROVISIONED:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_NOT_PROVISIONED,
    TSS2_FAPI_RC_ALREADY_PROVISIONED:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_ALREADY_PROVISIONED,
    TSS2_FAPI_RC_NULL_CALLBACK:
      layers.TSS2_FEATURE_RC_LAYER | base.TSS2_BASE_RC_CALLBACK_NULL,
  },
} as const;

export default enums;
